name: hatirlatici
description: "AI destekli Flutter hatırlatıcı uygulaması."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  flutter_local_notifications: ^22.2.0
  timezone: ^0.11.1
  flutter_timezone: ^5.1.0
  image_picker: ^1.2.3
  url_launcher: ^6.3.2
  file_picker: 10.3.10
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0D111A"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#0D111A"
  image: "assets/icon/splash_icon.png"
  android: true
  ios: true
  web: false

  android_12:
    color: "#0D111A"
    image: "assets/icon/splash_icon.png"